### ISSUE TITLE
Increased verbosity?

### ISSUE THREAD

**Issue by kallisti5** [jcaesar/ftp2mfs#18]
It would be nice to have a flag to get a bit more output.
Setting this up i'm greeted with a blank stare while it copies 100GiB+ into my ipfs repo lol.

**Comment by jcaesar** [comment]
You can set `RUST_LOG=info` in the environment for a log line for each copied file, but I guess I should make that the default if `RUST_LOG` isn't set.

**Comment by jcaesar** [comment]
All right, I polished the default setup. Would you mind giving it a spin, including the new command line option?
```
cargo install ftp2mfs --git https://github.com/jcaesar/ftp2mfs/ --rev a04fb4e5c674cc458bd296b03c9805912ba4fa37
```
(Needs at least rustc 1.54.)
